### ISSUE TITLE
[Ops] Sort out Jest warnings in Storyshots for mdx stories

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#754]
**Describe the bug**
Right now, even for successful test executions, there is a huge warning log dump on the console about the mdx stories transpilation for Storyshots:

For instance:
```
test/Storyshots.test.tsx (63.159s)
  ● Console

    console.warn
      Unexpected error while loading ./Alert/Alert.stories.mdx: SyntaxError: /home/circleci/repo/stories/Alert/Alert.stories.js: Support for the experimental syntax 'jsx' isn't currently enabled (21:10):
      
        19 |   ...props
        20 | }) {
      > 21 |   return <MDXLayout {...layoutProps} {...props} components={components} mdxType="MDXLayout">
           |          ^
        22 |
        23 |     <Meta title='Documentazione/Componenti/Alert' of={Alert} argTypes={{
        24 |       color: {
      
      Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
      If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

      at Object.warn (node_modules/@storybook/client-logger/dist/cjs/index.js:67:65)
      at node_modules/@storybook/core-client/dist/cjs/preview/loadCsf.js:92:34
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core-client/dist/cjs/preview/loadCsf.js:85:20
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core-client/dist/cjs/preview/loadCsf.js:84:12
      at ConfigApi.configure (node_modules/@storybook/client-api/dist/cjs/config_api.js:26:7)
      at Object.configure (node_modules/@storybook/core-client/dist/cjs/preview/loadCsf.js:254:17)
```

It would be nice to sort this out somehow.
It would be ok to skip mdx stories, as last resort, for Storyshots and keeping only the tsx stories to resolve it.

**To Reproduce**
1. Ran `yarn test` in the console
2. See the warnings

**Expected behavior**
No warnings

**Comment by toptalo** [comment]
Hi, I would like to work on it

**Comment by dej611** [comment]
What's your environment? Operating System / Node.JS version?

On Mac and Linux on Node.js there's the output above.

**Comment by toptalo** [comment]
Hmm. Very strange things happens =)
After I have get clean clone, have install and run test again now see same errors as in Issue.
Now will try to fix them.
