### ISSUE TITLE
[FEATURE] Update Component Callout - BC 2.4.0

### ISSUE THREAD

**Issue by sabato-galasso** [italia/design-react-kit#955]
**Describe the solution you'd like**

Update a Callout with Breaking change 2.4.0 component based on the original Bootstrap Italia Callout component:
https://italia.github.io/bootstrap-italia/docs/componenti/callout/

* [ ] Update the basic component
* [ ] Cover all the variants
* [ ] Create a Storybook set of stories based on the BI documentation

Notes:

* use BI classes to style the component.
* minimize the amount of extra CSS to style in this component

**Comment by federico-ntr** [comment]
I wanted to start working on this, but bumping BI's dependency from `^2.3.4` to `^2.4.0` results in errors when installing dependencies. This is what I get when I run `yarn`:

```
$ tsdx build --format cjs,esm && husky install
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
✓ Creating entry file 1 secs
⠸ Building modules
  188 |   const onEntering = React.useCallback((node, isAppearing) => {
  189 |     setHeight(getHeight(node));
> 190 |     attributes.onEntering?.(node, isAppearing);
      |                          ^ Unexpected token: punc (.)
  191 |   }, [attributes.onEntering]);
  192 |   const onEntered = React.useCallback((node, isAppearing) => {
(terser plugin) SyntaxError: Unexpected token: punc (.)
SyntaxError: Unexpected token: punc (.)
    at ne (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:19592)
    at c (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:28298)
    at l (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:28389)
    at f (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:28442)
    at U (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:42256)
    at me (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:48326)
    at /Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:49206
    at ve (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:49221)
    at ke (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:50475)
    at We (/Users/user/Documents/Progetti/Codespace/design-react-kit/node_modules/terser/dist/bundle.min.js:1:50707)

error Command failed with exit code 1.
```
